# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ramdu\Documents\YouDer-main\UI\main_ui.ui',
# licensing of 'c:\Users\ramdu\Documents\YouDer-main\UI\main_ui.ui' applies.
#
# Created: Sat Jan 29 19:29:12 2022
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_YouDer(object):
    def setupUi(self, YouDer):
        YouDer.setObjectName("YouDer")
        YouDer.resize(1127, 532)
        self.centralwidget = QtWidgets.QWidget(YouDer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_base = QtWidgets.QFrame(self.centralwidget)
        self.frame_base.setStyleSheet("")
        self.frame_base.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_base.setObjectName("frame_base")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_base)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_base)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_top.setStyleSheet("")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setLineWidth(0)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_toggle = QtWidgets.QFrame(self.frame_top)
        self.frame_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_toggle.setStyleSheet("")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setLineWidth(0)
        self.frame_toggle.setObjectName("frame_toggle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_toggle)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_toggle.sizePolicy().hasHeightForWidth())
        self.button_toggle.setSizePolicy(sizePolicy)
        self.button_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.button_toggle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_toggle.setStyleSheet("")
        self.button_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toggle/icons/white/toggle_hor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_toggle.setIcon(icon)
        self.button_toggle.setIconSize(QtCore.QSize(42, 42))
        self.button_toggle.setObjectName("button_toggle")
        self.horizontalLayout_3.addWidget(self.button_toggle)
        self.horizontalLayout_2.addWidget(self.frame_toggle)
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_right.sizePolicy().hasHeightForWidth())
        self.frame_top_right.setSizePolicy(sizePolicy)
        self.frame_top_right.setStyleSheet("")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.horizontalLayout_2.addWidget(self.frame_top_right)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_main = QtWidgets.QFrame(self.frame_base)
        self.frame_main.setStyleSheet("")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main_left = QtWidgets.QFrame(self.frame_main)
        self.frame_main_left.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_main_left.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_main_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_left.setLineWidth(0)
        self.frame_main_left.setObjectName("frame_main_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_main_left)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_for_button = QtWidgets.QFrame(self.frame_main_left)
        self.frame_for_button.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_for_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_button.setLineWidth(0)
        self.frame_for_button.setObjectName("frame_for_button")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_for_button)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_home = QtWidgets.QPushButton(self.frame_for_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_home.sizePolicy().hasHeightForWidth())
        self.button_home.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(14)
        self.button_home.setFont(font)
        self.button_home.setStyleSheet("")
        self.button_home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/home/icons/white/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_home.setIcon(icon1)
        self.button_home.setIconSize(QtCore.QSize(36, 36))
        self.button_home.setObjectName("button_home")
        self.verticalLayout_4.addWidget(self.button_home)
        self.button_settings = QtWidgets.QPushButton(self.frame_for_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_settings.sizePolicy().hasHeightForWidth())
        self.button_settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(14)
        self.button_settings.setFont(font)
        self.button_settings.setStyleSheet("")
        self.button_settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/settings/icons/white/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_settings.setIcon(icon2)
        self.button_settings.setIconSize(QtCore.QSize(24, 24))
        self.button_settings.setObjectName("button_settings")
        self.verticalLayout_4.addWidget(self.button_settings)
        self.button_history = QtWidgets.QPushButton(self.frame_for_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_history.sizePolicy().hasHeightForWidth())
        self.button_history.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(14)
        self.button_history.setFont(font)
        self.button_history.setStyleSheet("")
        self.button_history.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/history/icons/white/history_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_history.setIcon(icon3)
        self.button_history.setIconSize(QtCore.QSize(30, 30))
        self.button_history.setObjectName("button_history")
        self.verticalLayout_4.addWidget(self.button_history)
        self.verticalLayout_3.addWidget(self.frame_for_button)
        self.frame_at_middle_of_left = QtWidgets.QFrame(self.frame_main_left)
        self.frame_at_middle_of_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_at_middle_of_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_at_middle_of_left.setObjectName("frame_at_middle_of_left")
        self.verticalLayout_3.addWidget(self.frame_at_middle_of_left)
        self.frame_for_about_button = QtWidgets.QFrame(self.frame_main_left)
        self.frame_for_about_button.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_for_about_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_about_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_about_button.setLineWidth(0)
        self.frame_for_about_button.setObjectName("frame_for_about_button")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_for_about_button)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_about = QtWidgets.QPushButton(self.frame_for_about_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_about.sizePolicy().hasHeightForWidth())
        self.button_about.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(14)
        self.button_about.setFont(font)
        self.button_about.setStyleSheet("")
        self.button_about.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/about/icons/white/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_about.setIcon(icon4)
        self.button_about.setIconSize(QtCore.QSize(36, 36))
        self.button_about.setObjectName("button_about")
        self.verticalLayout_5.addWidget(self.button_about)
        self.verticalLayout_3.addWidget(self.frame_for_about_button)
        self.horizontalLayout.addWidget(self.frame_main_left)
        self.frame_mian_right = QtWidgets.QFrame(self.frame_main)
        self.frame_mian_right.setStyleSheet("")
        self.frame_mian_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_mian_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mian_right.setObjectName("frame_mian_right")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_mian_right)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pages = QtWidgets.QStackedWidget(self.frame_mian_right)
        self.pages.setStyleSheet("")
        self.pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pages.setLineWidth(0)
        self.pages.setMidLineWidth(0)
        self.pages.setObjectName("pages")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_home = QtWidgets.QFrame(self.page_home)
        self.frame_home.setStyleSheet("")
        self.frame_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home.setObjectName("frame_home")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_home)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_home_top = QtWidgets.QFrame(self.frame_home)
        self.frame_home_top.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_home_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_top.setLineWidth(0)
        self.frame_home_top.setObjectName("frame_home_top")
        self.layoutWidget = QtWidgets.QWidget(self.frame_home_top)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 612, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setSpacing(45)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_paste = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_paste.sizePolicy().hasHeightForWidth())
        self.button_paste.setSizePolicy(sizePolicy)
        self.button_paste.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.button_paste.setFont(font)
        self.button_paste.setStyleSheet("")
        self.button_paste.setText("Paste")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/paste/icons/white/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_paste.setIcon(icon5)
        self.button_paste.setIconSize(QtCore.QSize(16, 16))
        self.button_paste.setObjectName("button_paste")
        self.horizontalLayout_4.addWidget(self.button_paste)
        self.link_linedit = QtWidgets.QLineEdit(self.layoutWidget)
        self.link_linedit.setMinimumSize(QtCore.QSize(350, 25))
        self.link_linedit.setStyleSheet("")
        self.link_linedit.setObjectName("link_linedit")
        self.horizontalLayout_4.addWidget(self.link_linedit)
        self.button_getinfo = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_getinfo.sizePolicy().hasHeightForWidth())
        self.button_getinfo.setSizePolicy(sizePolicy)
        self.button_getinfo.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.button_getinfo.setFont(font)
        self.button_getinfo.setStyleSheet("")
        self.button_getinfo.setText("Get Info")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/getinfo/icons/white/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_getinfo.setIcon(icon6)
        self.button_getinfo.setIconSize(QtCore.QSize(16, 16))
        self.button_getinfo.setObjectName("button_getinfo")
        self.horizontalLayout_4.addWidget(self.button_getinfo)
        self.verticalLayout_8.addWidget(self.frame_home_top)
        self.frame_home_middle = QtWidgets.QFrame(self.frame_home)
        self.frame_home_middle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_middle.setObjectName("frame_home_middle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_home_middle)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_for_thumbnail = QtWidgets.QFrame(self.frame_home_middle)
        self.frame_for_thumbnail.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_for_thumbnail.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_for_thumbnail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_thumbnail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_thumbnail.setObjectName("frame_for_thumbnail")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_for_thumbnail)
        self.verticalLayout_9.setSpacing(15)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_for_thubnail_label = QtWidgets.QFrame(self.frame_for_thumbnail)
        self.frame_for_thubnail_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_thubnail_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_thubnail_label.setObjectName("frame_for_thubnail_label")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_for_thubnail_label)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.thubnail_label = QtWidgets.QLabel(self.frame_for_thubnail_label)
        self.thubnail_label.setText("")
        self.thubnail_label.setObjectName("thubnail_label")
        self.verticalLayout_10.addWidget(self.thubnail_label)
        self.verticalLayout_9.addWidget(self.frame_for_thubnail_label)
        self.frame_for_views = QtWidgets.QFrame(self.frame_for_thumbnail)
        self.frame_for_views.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_for_views.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_views.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_views.setObjectName("frame_for_views")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_for_views)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.eye_icon_label = QtWidgets.QLabel(self.frame_for_views)
        self.eye_icon_label.setText("")
        self.eye_icon_label.setPixmap(QtGui.QPixmap(":/eye/icons/white/eye.png"))
        self.eye_icon_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eye_icon_label.setObjectName("eye_icon_label")
        self.horizontalLayout_6.addWidget(self.eye_icon_label)
        self.views = QtWidgets.QLabel(self.frame_for_views)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.views.setFont(font)
        self.views.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.views.setObjectName("views")
        self.horizontalLayout_6.addWidget(self.views)
        self.video_length_icon_label = QtWidgets.QLabel(self.frame_for_views)
        self.video_length_icon_label.setText("")
        self.video_length_icon_label.setPixmap(QtGui.QPixmap(":/video_length/icons/white/video_length.png"))
        self.video_length_icon_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.video_length_icon_label.setObjectName("video_length_icon_label")
        self.horizontalLayout_6.addWidget(self.video_length_icon_label)
        self.length_label = QtWidgets.QLabel(self.frame_for_views)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.length_label.setFont(font)
        self.length_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.length_label.setObjectName("length_label")
        self.horizontalLayout_6.addWidget(self.length_label)
        self.verticalLayout_9.addWidget(self.frame_for_views)
        self.horizontalLayout_5.addWidget(self.frame_for_thumbnail)
        self.frame_for_title_and_combo = QtWidgets.QFrame(self.frame_home_middle)
        self.frame_for_title_and_combo.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_for_title_and_combo.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_for_title_and_combo.setFont(font)
        self.frame_for_title_and_combo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_title_and_combo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_title_and_combo.setObjectName("frame_for_title_and_combo")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_for_title_and_combo)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_for_title_label = QtWidgets.QFrame(self.frame_for_title_and_combo)
        self.frame_for_title_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_title_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_title_label.setObjectName("frame_for_title_label")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_for_title_label)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.title_label = QtWidgets.QLabel(self.frame_for_title_label)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(13)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_11.addWidget(self.title_label)
        self.verticalLayout_12.addWidget(self.frame_for_title_label)
        self.frame_for_combo_box = QtWidgets.QFrame(self.frame_for_title_and_combo)
        self.frame_for_combo_box.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_for_combo_box.setStyleSheet("")
        self.frame_for_combo_box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_combo_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_combo_box.setObjectName("frame_for_combo_box")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_for_combo_box)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.combobox = QtWidgets.QComboBox(self.frame_for_combo_box)
        self.combobox.setMinimumSize(QtCore.QSize(275, 25))
        self.combobox.setMaximumSize(QtCore.QSize(275, 16777215))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(10)
        self.combobox.setFont(font)
        self.combobox.setStyleSheet("")
        self.combobox.setObjectName("combobox")
        self.combobox.addItem("")
        self.combobox.addItem("")
        self.combobox.addItem("")
        self.verticalLayout_13.addWidget(self.combobox)
        self.verticalLayout_12.addWidget(self.frame_for_combo_box)
        self.horizontalLayout_5.addWidget(self.frame_for_title_and_combo)
        self.verticalLayout_8.addWidget(self.frame_home_middle)
        self.frame_home_bottom = QtWidgets.QFrame(self.frame_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_home_bottom.sizePolicy().hasHeightForWidth())
        self.frame_home_bottom.setSizePolicy(sizePolicy)
        self.frame_home_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_bottom.setLineWidth(0)
        self.frame_home_bottom.setObjectName("frame_home_bottom")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_home_bottom)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_for_progress = QtWidgets.QFrame(self.frame_home_bottom)
        self.frame_for_progress.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_for_progress.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_for_progress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_progress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_progress.setObjectName("frame_for_progress")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_for_progress)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem = QtWidgets.QSpacerItem(67, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem)
        self.frame_for_progress_top = QtWidgets.QFrame(self.frame_for_progress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_for_progress_top.sizePolicy().hasHeightForWidth())
        self.frame_for_progress_top.setSizePolicy(sizePolicy)
        self.frame_for_progress_top.setStyleSheet("")
        self.frame_for_progress_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_for_progress_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_progress_top.setObjectName("frame_for_progress_top")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_for_progress_top)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.status_bar = QtWidgets.QLabel(self.frame_for_progress_top)
        self.status_bar.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(11)
        self.status_bar.setFont(font)
        self.status_bar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.status_bar.setWordWrap(True)
        self.status_bar.setObjectName("status_bar")
        self.horizontalLayout_9.addWidget(self.status_bar)
        self.progressbar = QtWidgets.QProgressBar(self.frame_for_progress_top)
        self.progressbar.setMinimumSize(QtCore.QSize(150, 0))
        self.progressbar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressbar.setStyleSheet("")
        self.progressbar.setProperty("value", 54)
        self.progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbar.setObjectName("progressbar")
        self.horizontalLayout_9.addWidget(self.progressbar)
        self.verticalLayout_25.addWidget(self.frame_for_progress_top)
        self.horizontalLayout_7.addWidget(self.frame_for_progress)
        self.frame_for_download = QtWidgets.QFrame(self.frame_home_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_for_download.sizePolicy().hasHeightForWidth())
        self.frame_for_download.setSizePolicy(sizePolicy)
        self.frame_for_download.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_for_download.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_download.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_download.setObjectName("frame_for_download")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_for_download)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_for_save_as = QtWidgets.QFrame(self.frame_for_download)
        self.frame_for_save_as.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_save_as.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_save_as.setObjectName("frame_for_save_as")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_for_save_as)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.save_as_label = QtWidgets.QLabel(self.frame_for_save_as)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(10)
        self.save_as_label.setFont(font)
        self.save_as_label.setObjectName("save_as_label")
        self.horizontalLayout_10.addWidget(self.save_as_label)
        self.save_as_linedit = QtWidgets.QLineEdit(self.frame_for_save_as)
        self.save_as_linedit.setMinimumSize(QtCore.QSize(150, 0))
        self.save_as_linedit.setStyleSheet("")
        self.save_as_linedit.setObjectName("save_as_linedit")
        self.horizontalLayout_10.addWidget(self.save_as_linedit)
        self.toolButton = QtWidgets.QToolButton(self.frame_for_save_as)
        self.toolButton.setStyleSheet("")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_10.addWidget(self.toolButton)
        self.verticalLayout_14.addWidget(self.frame_for_save_as)
        self.frame_for_download_button = QtWidgets.QFrame(self.frame_for_download)
        self.frame_for_download_button.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_for_download_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_download_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_download_button.setObjectName("frame_for_download_button")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_for_download_button)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(269, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.download_button = QtWidgets.QPushButton(self.frame_for_download_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_button.sizePolicy().hasHeightForWidth())
        self.download_button.setSizePolicy(sizePolicy)
        self.download_button.setMinimumSize(QtCore.QSize(150, 45))
        self.download_button.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.download_button.setFont(font)
        self.download_button.setStyleSheet("")
        self.download_button.setText("Download")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/download/icons/white/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_button.setIcon(icon7)
        self.download_button.setIconSize(QtCore.QSize(24, 24))
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_8.addWidget(self.download_button)
        self.verticalLayout_14.addWidget(self.frame_for_download_button)
        self.horizontalLayout_7.addWidget(self.frame_for_download)
        self.verticalLayout_8.addWidget(self.frame_home_bottom)
        self.verticalLayout_7.addWidget(self.frame_home)
        self.pages.addWidget(self.page_home)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_settings)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_settings_main = QtWidgets.QFrame(self.page_settings)
        self.frame_settings_main.setStyleSheet("")
        self.frame_settings_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_settings_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_main.setObjectName("frame_settings_main")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_settings_main)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_settings_top = QtWidgets.QFrame(self.frame_settings_main)
        self.frame_settings_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_settings_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_top.setObjectName("frame_settings_top")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_settings_top)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_for_settings_widget = QtWidgets.QFrame(self.frame_settings_top)
        self.frame_for_settings_widget.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_for_settings_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_settings_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_settings_widget.setObjectName("frame_for_settings_widget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_for_settings_widget)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_3 = QtWidgets.QFrame(self.frame_for_settings_widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.choose_you_theme_label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(24)
        self.choose_you_theme_label.setFont(font)
        self.choose_you_theme_label.setStyleSheet("")
        self.choose_you_theme_label.setWordWrap(True)
        self.choose_you_theme_label.setObjectName("choose_you_theme_label")
        self.verticalLayout_19.addWidget(self.choose_you_theme_label)
        self.verticalLayout_18.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_for_settings_widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 241, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.night_mode_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.night_mode_label.setFont(font)
        self.night_mode_label.setStyleSheet("")
        self.night_mode_label.setObjectName("night_mode_label")
        self.horizontalLayout_13.addWidget(self.night_mode_label)
        self.dark_mode_onoff_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.dark_mode_onoff_button.setMaximumSize(QtCore.QSize(80, 30))
        self.dark_mode_onoff_button.setStyleSheet("")
        self.dark_mode_onoff_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toggle_off/icons/white/toggle_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dark_mode_onoff_button.setIcon(icon8)
        self.dark_mode_onoff_button.setIconSize(QtCore.QSize(80, 30))
        self.dark_mode_onoff_button.setObjectName("dark_mode_onoff_button")
        self.horizontalLayout_13.addWidget(self.dark_mode_onoff_button)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 80, 321, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.default_radio_button = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(14)
        self.default_radio_button.setFont(font)
        self.default_radio_button.setStyleSheet("")
        self.default_radio_button.setObjectName("default_radio_button")
        self.horizontalLayout_12.addWidget(self.default_radio_button)
        self.green_radio_button = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(14)
        self.green_radio_button.setFont(font)
        self.green_radio_button.setStyleSheet("")
        self.green_radio_button.setObjectName("green_radio_button")
        self.horizontalLayout_12.addWidget(self.green_radio_button)
        self.pink_radio_button = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(14)
        self.pink_radio_button.setFont(font)
        self.pink_radio_button.setStyleSheet("")
        self.pink_radio_button.setObjectName("pink_radio_button")
        self.horizontalLayout_12.addWidget(self.pink_radio_button)
        self.verticalLayout_18.addWidget(self.frame_4)
        self.horizontalLayout_11.addWidget(self.frame_for_settings_widget)
        self.frame_for_gear_icon = QtWidgets.QFrame(self.frame_settings_top)
        self.frame_for_gear_icon.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_for_gear_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_gear_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_gear_icon.setObjectName("frame_for_gear_icon")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_for_gear_icon)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_for_gear_icon = QtWidgets.QLabel(self.frame_for_gear_icon)
        self.label_for_gear_icon.setText("")
        self.label_for_gear_icon.setPixmap(QtGui.QPixmap(":/gear_icon/icons/white/settings_gear.png"))
        self.label_for_gear_icon.setObjectName("label_for_gear_icon")
        self.verticalLayout_17.addWidget(self.label_for_gear_icon)
        self.horizontalLayout_11.addWidget(self.frame_for_gear_icon)
        self.verticalLayout_16.addWidget(self.frame_settings_top)
        self.frame_settings_bottom = QtWidgets.QFrame(self.frame_settings_main)
        self.frame_settings_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings_bottom.setObjectName("frame_settings_bottom")
        self.frame_for_download_location = QtWidgets.QFrame(self.frame_settings_bottom)
        self.frame_for_download_location.setGeometry(QtCore.QRect(20, 50, 401, 40))
        self.frame_for_download_location.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_download_location.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_download_location.setObjectName("frame_for_download_location")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_for_download_location)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.download_location_label = QtWidgets.QLabel(self.frame_for_download_location)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.download_location_label.setFont(font)
        self.download_location_label.setStyleSheet("")
        self.download_location_label.setObjectName("download_location_label")
        self.horizontalLayout_22.addWidget(self.download_location_label)
        self.download_location_linedit = QtWidgets.QLineEdit(self.frame_for_download_location)
        self.download_location_linedit.setMinimumSize(QtCore.QSize(150, 0))
        self.download_location_linedit.setStyleSheet("")
        self.download_location_linedit.setObjectName("download_location_linedit")
        self.horizontalLayout_22.addWidget(self.download_location_linedit)
        self.download_location_tool_button = QtWidgets.QToolButton(self.frame_for_download_location)
        self.download_location_tool_button.setStyleSheet("")
        self.download_location_tool_button.setObjectName("download_location_tool_button")
        self.horizontalLayout_22.addWidget(self.download_location_tool_button)
        self.verticalLayout_16.addWidget(self.frame_settings_bottom)
        self.verticalLayout_15.addWidget(self.frame_settings_main)
        self.pages.addWidget(self.page_settings)
        self.page_history = QtWidgets.QWidget()
        self.page_history.setAutoFillBackground(False)
        self.page_history.setObjectName("page_history")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.page_history)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_left = QtWidgets.QFrame(self.page_history)
        self.frame_left.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame = QtWidgets.QFrame(self.frame_left)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.title_history_label = QtWidgets.QLabel(self.frame)
        self.title_history_label.setGeometry(QtCore.QRect(40, 20, 321, 84))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(24)
        self.title_history_label.setFont(font)
        self.title_history_label.setStyleSheet("")
        self.title_history_label.setWordWrap(True)
        self.title_history_label.setObjectName("title_history_label")
        self.verticalLayout_29.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_left)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(250, 220))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_for_gear_icon_2 = QtWidgets.QLabel(self.frame_5)
        self.label_for_gear_icon_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_for_gear_icon_2.setText("")
        self.label_for_gear_icon_2.setPixmap(QtGui.QPixmap(":/history/icons/white/history_white.png"))
        self.label_for_gear_icon_2.setScaledContents(True)
        self.label_for_gear_icon_2.setObjectName("label_for_gear_icon_2")
        self.verticalLayout_31.addWidget(self.label_for_gear_icon_2)
        self.horizontalLayout_19.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(246, 228))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 150, 241, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.track_history_label = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.track_history_label.setFont(font)
        self.track_history_label.setStyleSheet("")
        self.track_history_label.setObjectName("track_history_label")
        self.horizontalLayout_20.addWidget(self.track_history_label)
        self.track_downloads_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.track_downloads_button.setMaximumSize(QtCore.QSize(80, 30))
        self.track_downloads_button.setStyleSheet("")
        self.track_downloads_button.setText("")
        self.track_downloads_button.setIcon(icon8)
        self.track_downloads_button.setIconSize(QtCore.QSize(80, 30))
        self.track_downloads_button.setObjectName("track_downloads_button")
        self.horizontalLayout_20.addWidget(self.track_downloads_button)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 40, 241, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_21.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.history_delete_label = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.history_delete_label.setFont(font)
        self.history_delete_label.setStyleSheet("")
        self.history_delete_label.setObjectName("history_delete_label")
        self.horizontalLayout_21.addWidget(self.history_delete_label)
        self.history_delete_button = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_delete_button.sizePolicy().hasHeightForWidth())
        self.history_delete_button.setSizePolicy(sizePolicy)
        self.history_delete_button.setMaximumSize(QtCore.QSize(30, 50))
        self.history_delete_button.setStyleSheet("")
        self.history_delete_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/history/icons/white/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_delete_button.setIcon(icon9)
        self.history_delete_button.setIconSize(QtCore.QSize(50, 30))
        self.history_delete_button.setObjectName("history_delete_button")
        self.horizontalLayout_21.addWidget(self.history_delete_button)
        self.horizontalLayout_19.addWidget(self.frame_6)
        self.verticalLayout_29.addWidget(self.frame_2)
        self.horizontalLayout_17.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(self.page_history)
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_right)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 477, 435))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.history_layout = QtWidgets.QVBoxLayout()
        self.history_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.history_layout.setContentsMargins(10, 0, 10, 0)
        self.history_layout.setObjectName("history_layout")
        self.verticalLayout_28.addLayout(self.history_layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_27.addWidget(self.scrollArea)
        self.horizontalLayout_17.addWidget(self.frame_right)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.pages.addWidget(self.page_history)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_about)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_about_main = QtWidgets.QFrame(self.page_about)
        self.frame_about_main.setStyleSheet("")
        self.frame_about_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_about_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_about_main.setObjectName("frame_about_main")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_about_main)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_about_main_bottom = QtWidgets.QFrame(self.frame_about_main)
        self.frame_about_main_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_about_main_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_about_main_bottom.setObjectName("frame_about_main_bottom")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_about_main_bottom)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_about_main_left = QtWidgets.QFrame(self.frame_about_main_bottom)
        self.frame_about_main_left.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_about_main_left.setMaximumSize(QtCore.QSize(250, 300))
        self.frame_about_main_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_about_main_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_about_main_left.setObjectName("frame_about_main_left")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_about_main_left)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_for_logo = QtWidgets.QLabel(self.frame_about_main_left)
        self.label_for_logo.setText("")
        self.label_for_logo.setPixmap(QtGui.QPixmap(":/icon/icons/icon.png"))
        self.label_for_logo.setScaledContents(True)
        self.label_for_logo.setObjectName("label_for_logo")
        self.verticalLayout_22.addWidget(self.label_for_logo)
        self.horizontalLayout_14.addWidget(self.frame_about_main_left)
        self.frame_about_main_right = QtWidgets.QFrame(self.frame_about_main_bottom)
        self.frame_about_main_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_about_main_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_about_main_right.setObjectName("frame_about_main_right")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_about_main_right)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_for_info_label = QtWidgets.QFrame(self.frame_about_main_right)
        self.frame_for_info_label.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_for_info_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_info_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_info_label.setObjectName("frame_for_info_label")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_for_info_label)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_info = QtWidgets.QLabel(self.frame_for_info_label)
        self.label_info.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(16)
        self.label_info.setFont(font)
        self.label_info.setStyleSheet("")
        self.label_info.setWordWrap(True)
        self.label_info.setObjectName("label_info")
        self.verticalLayout_24.addWidget(self.label_info)
        self.verticalLayout_23.addWidget(self.frame_for_info_label)
        self.frame_for_info_extra_links = QtWidgets.QFrame(self.frame_about_main_right)
        self.frame_for_info_extra_links.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_info_extra_links.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_info_extra_links.setObjectName("frame_for_info_extra_links")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_for_info_extra_links)
        self.horizontalLayout_15.setSpacing(20)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(296, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.youtube_button = QtWidgets.QPushButton(self.frame_for_info_extra_links)
        self.youtube_button.setStyleSheet("QPushButton{\n"
"border:none;\n"
"\n"
"\n"
"\n"
"}")
        self.youtube_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/youtube_icon/icons/black/youtube_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.youtube_button.setIcon(icon10)
        self.youtube_button.setIconSize(QtCore.QSize(64, 64))
        self.youtube_button.setObjectName("youtube_button")
        self.horizontalLayout_15.addWidget(self.youtube_button)
        self.telegram_button = QtWidgets.QPushButton(self.frame_for_info_extra_links)
        self.telegram_button.setStyleSheet("QPushButton{\n"
"border:none;\n"
"\n"
"\n"
"\n"
"}")
        self.telegram_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/telegram/icons/white/telegram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.telegram_button.setIcon(icon11)
        self.telegram_button.setIconSize(QtCore.QSize(64, 64))
        self.telegram_button.setObjectName("telegram_button")
        self.horizontalLayout_15.addWidget(self.telegram_button)
        self.github_button = QtWidgets.QPushButton(self.frame_for_info_extra_links)
        self.github_button.setStyleSheet("QPushButton{\n"
"border:none;\n"
"\n"
"\n"
"\n"
"}")
        self.github_button.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/github/icons/white/github_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.github_button.setIcon(icon12)
        self.github_button.setIconSize(QtCore.QSize(64, 64))
        self.github_button.setObjectName("github_button")
        self.horizontalLayout_15.addWidget(self.github_button)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.verticalLayout_23.addWidget(self.frame_for_info_extra_links)
        self.horizontalLayout_14.addWidget(self.frame_about_main_right)
        self.verticalLayout_21.addWidget(self.frame_about_main_bottom)
        self.frame_about_main_top = QtWidgets.QFrame(self.frame_about_main)
        self.frame_about_main_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_about_main_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_about_main_top.setObjectName("frame_about_main_top")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_about_main_top)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem5 = QtWidgets.QSpacerItem(750, 126, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem6)
        self.version_label = QtWidgets.QLabel(self.frame_about_main_top)
        self.version_label.setMinimumSize(QtCore.QSize(250, 0))
        self.version_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(12)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.verticalLayout_26.addWidget(self.version_label)
        self.horizontalLayout_16.addLayout(self.verticalLayout_26)
        self.verticalLayout_21.addWidget(self.frame_about_main_top)
        self.verticalLayout_20.addWidget(self.frame_about_main)
        self.pages.addWidget(self.page_about)
        self.verticalLayout_6.addWidget(self.pages)
        self.horizontalLayout.addWidget(self.frame_mian_right)
        self.verticalLayout_2.addWidget(self.frame_main)
        self.verticalLayout.addWidget(self.frame_base)
        YouDer.setCentralWidget(self.centralwidget)

        self.retranslateUi(YouDer)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(YouDer)

    def retranslateUi(self, YouDer):
        YouDer.setWindowTitle(QtWidgets.QApplication.translate("YouDer", "MainWindow", None, -1))
        self.views.setText(QtWidgets.QApplication.translate("YouDer", "125K", None, -1))
        self.length_label.setText(QtWidgets.QApplication.translate("YouDer", "00:00:00", None, -1))
        self.title_label.setText(QtWidgets.QApplication.translate("YouDer", "You Der is Free Open Sourced Youtube video downloader by Open utilites.....", None, -1))
        self.combobox.setItemText(0, QtWidgets.QApplication.translate("YouDer", "1080p Video- 45 Mb", None, -1))
        self.combobox.setItemText(1, QtWidgets.QApplication.translate("YouDer", " 720p Video- 33 Mb", None, -1))
        self.combobox.setItemText(2, QtWidgets.QApplication.translate("YouDer", "480p Video- 24 Mb", None, -1))
        self.status_bar.setText(QtWidgets.QApplication.translate("YouDer", "Progress :", None, -1))
        self.save_as_label.setText(QtWidgets.QApplication.translate("YouDer", "Save as", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("YouDer", "...", None, -1))
        self.choose_you_theme_label.setText(QtWidgets.QApplication.translate("YouDer", "Choose your Theme . . . ", None, -1))
        self.night_mode_label.setText(QtWidgets.QApplication.translate("YouDer", "Night Mode ", None, -1))
        self.default_radio_button.setText(QtWidgets.QApplication.translate("YouDer", "Default", None, -1))
        self.green_radio_button.setText(QtWidgets.QApplication.translate("YouDer", "Green", None, -1))
        self.pink_radio_button.setText(QtWidgets.QApplication.translate("YouDer", "Pink", None, -1))
        self.download_location_label.setText(QtWidgets.QApplication.translate("YouDer", "Download Location", None, -1))
        self.download_location_tool_button.setText(QtWidgets.QApplication.translate("YouDer", "...", None, -1))
        self.title_history_label.setText(QtWidgets.QApplication.translate("YouDer", "Previous Downloads ... ", None, -1))
        self.track_history_label.setText(QtWidgets.QApplication.translate("YouDer", "Track Dowloads", None, -1))
        self.history_delete_label.setText(QtWidgets.QApplication.translate("YouDer", "Delete History", None, -1))
        self.label_info.setText(QtWidgets.QApplication.translate("YouDer", "<html><head/><body><p><span style=\" font-weight:600;\">YouDer</span> is Free ,Open Sourced Youtube Video Downloader.YouDer is build on <span style=\" font-weight:600;\">Qt,Pytube</span> and <span style=\" font-weight:600;\">Python.</span>YouDer is a product of <span style=\" font-weight:600;\">OpenUtilites</span>.</p></body></html>", None, -1))
        self.version_label.setText(QtWidgets.QApplication.translate("YouDer", "YouDer Version 2.0", None, -1))
